server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-microservice:8081
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**

        - id: notifications-service
          uri: http://notifications-service:8083
          predicates:
            - Path=/notifications/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO