server:
    port: 8080


spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://localhost:8081
            predicates:
              - Path=/user/**
          - id: auth-service
            uri: http://localhost:8082
            predicates:
              - Path=/auth/**