server:
    port: 8080
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://microservice-user:8081
            predicates:
              - Path=/user/**
          - id: auth-service
            uri: http://microservice-auth:8082
            predicates:
              - Path=/auth/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO