apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microservice
  labels:
    app: gateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice
          image: juanhoyos/microservice:gateway-v34
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: jwt
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
